### ISSUE TITLE
Benchmark Question

### ISSUE THREAD

**Issue by ZhengxuYan** [zhuzilin/ring-flash-attention#49]
Hi

Benchmarking shows that the non-varlen version of ring_attn performs worse than flash_attn, both in iterations per second and CUDA memory usage. Is this expected, or should it theoretically perform better?

Thanks!

**Comment by ZhengxuYan** [comment]
When running the benchmark with 8 GPUs, why does the Flash Attention code require only 1/8 of the computation of Ring Attention? Sorry if this is a silly question.

**Comment by zhuzilin** [comment]
> Benchmarking shows that the non-varlen version of ring_attn performs worse than flash_attn, both in iterations per second and CUDA memory usage. Is this expected, or should it theoretically perform better?

This is expected. You can consider ring_flash_attn as flash_attn with some memory and communication overhead to support the long context that could not be held on single GPU. The actually computation is still done with flash_attn. So in terms of speed, ring_attn should be slower than flash attn.

> When running the benchmark with 8 GPUs, why does the Flash Attention code require only 1/8 of the computation of Ring Attention?

This is because the ring attn is running the attention of a 8 * seqlen long data, as the computation of the attention is `O(seqlen^2)`, the computation of the ring attn is ~ 64 * seqlen^2.

While in the flash attn case, it's 8 gpu running seqlen^2 separately, so the total computation is ~ 8 * seqlen^2.
